version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    groups:
      all-go-mod-patch-and-minor:
        patterns: ["*"]
        update-types: ["patch", "minor"]
    ignore:
      - dependency-name: github.com/mesosphere/konvoy-async-auth
        versions:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
